FROM amd64/python:3.7-slim-buster

WORKDIR /app

ADD ./test_image_0.jpg .
ADD ./test_image_1.jpg .
ADD ./test_image_2.jpg .
ADD ./test_image_3.jpg .
ADD ./test_image_4.jpg .
ADD ./test_image_5.jpg .

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]